"""empty message

Revision ID: f7d2f4aaa14c
Revises: c8060b679e71
Create Date: 2024-12-08 00:55:38.766207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d2f4aaa14c'
down_revision: Union[str, None] = 'c8060b679e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accessory_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('category_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_fk'], ['category_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accessory_table')
    op.drop_table('category_table')
    # ### end Alembic commands ###
